/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-18 12:21:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class userfooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>wildHaven</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	  <!-- Footer Start -->\r\n");
      out.write("  <div class=\"container-fluid footer bg-dark text-light footer mt-5 pt-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("      <div class=\"row g-5\">\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("          <h5 class=\"text-light mb-4\">Address</h5>\r\n");
      out.write("          <p class=\"mb-2\">\r\n");
      out.write("            <i class=\"fa fa-map-marker-alt me-3\"></i>Bhubaneswar, Odisha, India\r\n");
      out.write("          </p>\r\n");
      out.write("          <p class=\"mb-2\">\r\n");
      out.write("            <i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890\r\n");
      out.write("          </p>\r\n");
      out.write("          <p class=\"mb-2\">\r\n");
      out.write("            <i class=\"fa fa-envelope me-3\"></i>team.wildhaven@gmail.com\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"d-flex pt-2\">\r\n");
      out.write("            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("          <h5 class=\"text-light mb-4\">Quick Links</h5>\r\n");
      out.write("          <a class=\"btn btn-link\" href=\"about.jsp\">About Us</a>\r\n");
      out.write("       \r\n");
      out.write("          <a class=\"btn btn-link\" href=\"conservation.jsp\">Our Services</a>\r\n");
      out.write("          <a class=\"btn btn-link\" href=\"#\">Terms & Condition</a>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("          <h5 class=\"text-light mb-4\">Popular Links</h5>\r\n");
      out.write("          <a class=\"btn btn-link\" href=\"https://bigcatsindia.com/\">Bigcats India</a>\r\n");
      out.write("          <a class=\"btn btn-link\" href=\"https://www.tigersafariindia.com/\">Tiger Safari</a>\r\n");
      out.write("          <a class=\"btn btn-link\" href=\"https://www.similipal.org/\">Similipal Reserve</a>\r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("          <h5 class=\"text-light mb-4\">Welcome to the WildHaven Newsletter</h5>\r\n");
      out.write("           <p>Join our newsletter to stay updated on our latest wildlife conservation efforts and success stories.</p>\r\n");
      out.write("          <div class=\"position-relative mx-auto\" style=\"max-width: 400px\">\r\n");
      out.write("            <input class=\"form-control border-0 w-100 py-3 ps-4 pe-5\" type=\"text\" placeholder=\"Your email\" />\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2\">\r\n");
      out.write("              SignUp\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("            &copy; <a class=\"border-bottom\" href=\"#\">WildHaven</a>, All\r\n");
      out.write("            Right Reserved.\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 text-center text-md-end\" style=\"display: none !important;\">\r\n");
      out.write("            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("            Designed By\r\n");
      out.write("            <a class=\"border-bottom\" href=\"#\"></a>\r\n");
      out.write("            <br />Distributed By:\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Back to Top -->\r\n");
      out.write("  <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- JavaScript Libraries -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Javascript -->\r\n");
      out.write("  <script src=\"js1/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("  window.watsonAssistantChatOptions = {\r\n");
      out.write("    integrationID: \"40f6535b-f4fd-4da5-9334-91599b86c0b0\", // The ID of this integration.\r\n");
      out.write("    region: \"au-syd\", // The region your integration is hosted in.\r\n");
      out.write("    serviceInstanceID: \"eab37542-ac5e-4718-8d4f-787f12a29357\", // The ID of your service instance.\r\n");
      out.write("    onLoad: async (instance) => { await instance.render(); }\r\n");
      out.write("  };\r\n");
      out.write("  setTimeout(function(){\r\n");
      out.write("    const t=document.createElement('script');\r\n");
      out.write("    t.src=\"https://web-chat.global.assistant.watson.appdomain.cloud/versions/\" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + \"/WatsonAssistantChatEntry.js\";\r\n");
      out.write("    document.head.appendChild(t);\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
