/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-19 09:25:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "userheader.jsp", out, false);
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <title>WildHaven |Wildlife Conservation & Protection System</title>\r\n");
      out.write(" \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("   /* Ensure the carousel and its items take up the full height of the column */\r\n");
      out.write(".carousel, .carousel-inner, .carousel-item {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-item img {\r\n");
      out.write("  \r\n");
      out.write("    width: 120%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("     margin-left: -5%; /* Center the image horizontally */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style carousel controls */\r\n");
      out.write(".carousel-control-prev-icon,\r\n");
      out.write(".carousel-control-next-icon {\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.5); /* Dark background for visibility */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style carousel indicators */\r\n");
      out.write(".carousel-indicators button {\r\n");
      out.write("    background-color: #007bff; /* Primary color for indicators */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some spacing between carousel items */\r\n");
      out.write(".carousel-item {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Container and Section Styling */\r\n");
      out.write(".container-xxl {\r\n");
      out.write("    padding: 5rem 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Row Styling */\r\n");
      out.write(".row.g-4 {\r\n");
      out.write("    justify-content: center; /* Center all team items in the row */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Team Item Container */\r\n");
      out.write(".team-item {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    margin: 0 auto; /* Center the team item */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-img-container {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    margin: 0 auto; /* Center the image */\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    border: 5px solid #fff; /* Optional: Add a b/* Team Item Container */\r\n");
      out.write("    }\r\n");
      out.write(".team-item {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    margin: 0 auto; /* Center the team item */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-img-container {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    margin: 0 auto; /* Center the image */\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    border: 5px solid #fff; /* Optional: Add a border around the circle */\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Optional: Add a subtle shadow for depth */\r\n");
      out.write("}\r\n");
      out.write(".team-img-container:hover {\r\n");
      out.write("    transform: scale(1.1); /* Slight zoom on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    border-radius: 50%;order around the circle */\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Optional: Add a subtle shadow for depth */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("\r\n");
      out.write("/* Hover Effects */\r\n");
      out.write(".team-item:hover {\r\n");
      out.write("    transform: translateY(-10px);\r\n");
      out.write("    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-img-container:hover .team-img {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Team Text Styling */\r\n");
      out.write(".team-text h4 {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("/* Base button styling */\r\n");
      out.write(".team-social .btn {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    line-height: 40px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #fff; /* White color for icons */\r\n");
      out.write("    font-size: 18px; /* Adjust the font size for icons */\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("    border: none; /* Remove border if any */\r\n");
      out.write("    display: inline-flex; /* Align items inside the button */\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Facebook button */\r\n");
      out.write(".btn-facebook {\r\n");
      out.write("    background-color: #3b5998; /* Facebook blue */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-facebook:hover {\r\n");
      out.write("    background-color: #2d4373; /* Darker Facebook blue on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Twitter button */\r\n");
      out.write(".btn-twitter {\r\n");
      out.write("    background-color: #1da1f2; /* Twitter blue */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-twitter:hover {\r\n");
      out.write("    background-color: #0d95e8; /* Darker Twitter blue on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* LinkedIn button */\r\n");
      out.write(".btn-linkedin {\r\n");
      out.write("    background-color: #0077b5; /* LinkedIn blue */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-linkedin:hover {\r\n");
      out.write("    background-color: #005582; /* Darker LinkedIn blue on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Ensure the buttons are centered within the team-social container */\r\n");
      out.write(".team-social {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Responsive Design */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .team-item {\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 576px) {\r\n");
      out.write("    .team-img-container {\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        height: 120px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .team-text h4 {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Species Section */\r\n");
      out.write(".species-item {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-item:hover {\r\n");
      out.write("    border-color: #28a745; /* Green border on hover */\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-item img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-item:hover img {\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-text {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-text h4 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".species-text p {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   /* Ensure the image covers the full width and is responsive */\r\n");
      out.write("img.img-fluid {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Optionally, you can add a class for full-width image styling */\r\n");
      out.write(".full-width-img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Header Start -->\r\n");
      out.write("    <div\r\n");
      out.write("      class=\"container-fluid header-bg py-5 mb-5 wow fadeIn\"\r\n");
      out.write("      data-wow-delay=\"0.1s\"\r\n");
      out.write("    >\r\n");
      out.write("      <div class=\"container py-5\">\r\n");
      out.write("        <h1 class=\"display-4 text-white mb-3 animated slideInDown\">About Us</h1>\r\n");
      out.write("        <nav aria-label=\"breadcrumb animated slideInDown\">\r\n");
      out.write("        \r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Page Header End -->\r\n");
      out.write("<!-- About Start -->\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row g-5\">\r\n");
      out.write("            <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                \r\n");
      out.write("                <h1 class=\"display-5 mb-4\">\r\n");
      out.write("                    Safeguarding Wildlife with\r\n");
      out.write("                    <span class=\"text-primary\">WildHaven</span>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <p class=\"mb-4\" style=text-align:justify;>\r\n");
      out.write("                    WildGuard is dedicated to the conservation and protection of wildlife through innovative technology, comprehensive research, and active community involvement. Our mission is to ensure the survival of endangered species and the preservation of their natural habitats.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"mb-4\" style=text-align:justify;>\r\n");
      out.write("                    We leverage modern technology to monitor and protect wildlife populations, analyze data to inform conservation strategies, and engage with local communities to foster sustainable practices. Join us in our mission to create a safer world for wildlife.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"accordion\" id=\"wildlifeAccordion\">\r\n");
      out.write("                    <div class=\"accordion-item\">\r\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"headingOne\">\r\n");
      out.write("                            <button class=\"accordion-button\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("                                <i class=\"fas fa-plus-circle text-primary me-3\"></i>Monitoring Endangered Species\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <div id=\"collapseOne\" class=\"accordion-collapse collapse show\" aria-labelledby=\"headingOne\" data-bs-parent=\"#wildlifeAccordion\">\r\n");
      out.write("                            <div class=\"accordion-body\">\r\n");
      out.write("                                Utilizing advanced tracking systems and data analytics to monitor the health and movement of endangered species.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"accordion-item\">\r\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"headingTwo\">\r\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                                <i class=\"fas fa-plus-circle text-primary me-3\"></i>Conservation Initiatives\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingTwo\" data-bs-parent=\"#wildlifeAccordion\">\r\n");
      out.write("                            <div class=\"accordion-body\">\r\n");
      out.write("                                Implementing targeted conservation projects to restore habitats and protect wildlife from threats such as poaching and climate change.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"accordion-item\">\r\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"headingThree\">\r\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("                                <i class=\"fas fa-plus-circle text-primary me-3\"></i>Scientific Research\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <div id=\"collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingThree\" data-bs-parent=\"#wildlifeAccordion\">\r\n");
      out.write("                            <div class=\"accordion-body\">\r\n");
      out.write("                                Conducting cutting-edge research to better understand wildlife behavior, health, and ecology, informing our conservation strategies.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"accordion-item\">\r\n");
      out.write("                        <h2 class=\"accordion-header\" id=\"headingFour\">\r\n");
      out.write("                            <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n");
      out.write("                                <i class=\"fas fa-plus-circle text-primary me-3\"></i>Community Engagement\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <div id=\"collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFour\" data-bs-parent=\"#wildlifeAccordion\">\r\n");
      out.write("                            <div class=\"accordion-body\">\r\n");
      out.write("                                Educating and involving local communities in conservation efforts to ensure sustainable and effective protection measures.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"btn btn-primary py-3 px-5 mt-3\" href=\"https://www.wcs.org/\">Learn More</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <div id=\"carouselExampleIndicators\" class=\"carousel slide\">\r\n");
      out.write("                    <div class=\"carousel-inner\">\r\n");
      out.write("                        <div class=\"carousel-item active\">\r\n");
      out.write("                            <img src=\"img/endangerspecies.jpg\" class=\"d-block w-100\" alt=\"Monitoring Endangered Species\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">\r\n");
      out.write("                            <img src=\"img/trust.jpg\" class=\"d-block w-100\" alt=\"Conservation Initiatives\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">\r\n");
      out.write("                            <img src=\"img/scientific.jpg\" class=\"d-block w-100\" alt=\"Scientific Research\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">\r\n");
      out.write("                            <img src=\"img/community.jpg\" class=\"d-block w-100\" alt=\"Community Engagement\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("                        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("                        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- About End -->\r\n");
      out.write(" \r\n");
      out.write("<!-- Team start -->\r\n");
      out.write("<!-- Team Start -->\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("            <p class=\"d-inline-block border rounded text-primary fw-semi-bold py-1 px-3\">Our Team</p>\r\n");
      out.write("            <h1 class=\"display-5 mb-5\">Meet Our <b class=text-primary>Team</b></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <div class=\"team-item\">\r\n");
      out.write("                    <div class=\"team-img-container\">\r\n");
      out.write("                        <img class=\"img-fluid rounded-circle team-img\" src=\"img/Jitesh.png\" alt=\"Jitesh Mohapatra\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-text\">\r\n");
      out.write("                        <h4 class=\"mb-0\">Jitesh Mohapatra</h4>\r\n");
      out.write("                      <div class=\"team-social d-flex justify-content-center mt-3\">\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-facebook\" href=\"https://www.facebook.com/jitesh.mohapatra.77\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-twitter\" href=\"https://x.com/MohapatraJitesh\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-linkedin\" href=\"https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3Bi3UOjx1zRay5EHfG0k2KOA%3D%3D\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("                      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                 </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                <div class=\"team-item\">\r\n");
      out.write("                    <div class=\"team-img-container\">\r\n");
      out.write("                        <img class=\"img-fluid rounded-circle team-img\" src=\"img/kumar_rakshit.png\" alt=\"Sayan Kumar Rakshit\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-text\">\r\n");
      out.write("                        <h4 class=\"mb-0\">Sayan Kumar Rakshit</h4>\r\n");
      out.write("                    <div class=\"team-social d-flex justify-content-center mt-3\">\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-facebook\" href=\"https://www.facebook.com/er.sayanrakshit\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-twitter\" href=\"https://x.com/Binary_Sayan\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-linkedin\" href=\"https://www.linkedin.com/in/sayanrakshit2004/\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                <div class=\"team-item\">\r\n");
      out.write("                    <div class=\"team-img-container\">\r\n");
      out.write("                        <img class=\"img-fluid rounded-circle team-img\" src=\"img/Akash.png\" alt=\"Santosh Baral\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-text\">\r\n");
      out.write("                        <h4 class=\"mb-0\">Santosh Baral</h4>\r\n");
      out.write("                        <div class=\"team-social d-flex justify-content-center mt-3\">\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-facebook\" href=\"https://www.facebook.com/kingsman.santosh.1\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-twitter\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("    <a class=\"btn btn-square rounded-circle mx-1 btn-linkedin\" href=\"https://www.linkedin.com/in/santoshkubaral/\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Team End -->\r\n");
      out.write("\r\n");
      out.write("<!-- About Start -->\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("            <p class=\"d-inline-block border rounded text-primary fw-semi-bold py-1 px-3\">About Us</p>\r\n");
      out.write("            <h1 class=\"display-5 mb-5\">Dedicated to <b class=\"text-primary\">Wildlife Conservation</b></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-12 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <img class=\"img-fluid rounded w-100\" src=\"img/7.png\" alt=\"Wildlife Conservation\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- About End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Contact Start -->\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 600px;\">\r\n");
      out.write("            <p class=\"d-inline-block border rounded text-primary fw-semi-bold py-1 px-3\">Contact Us</p>\r\n");
      out.write("            <h1 class=\"display-5 mb-5\"><b class=\"text-primary\">Get in</b> Touch</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"name\" class=\"form-label\">Your Name</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"email\" class=\"form-label\">Your Email</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Your Email\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"subject\" class=\"form-label\">Subject</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"subject\" placeholder=\"Subject\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"message\" class=\"form-label\">Message</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"message\" placeholder=\"Message\" rows=\"5\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary w-100 py-3\">Send Message</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 text-center wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                <div class=\"map-frame\">\r\n");
      out.write("                   <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3741.739216352266!2d85.84664707469565!3d20.311058712042794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a190b237f405e7b%3A0x776ac97fec34db8b!2sNSTI%20BHUBANESWAR%20Macheswar%20Campus!5e0!3m2!1sen!2sin!4v1723108325377!5m2!1sen!2sin\" width=\"600\" height=\"500\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Contact End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Testimonial Start -->\r\n");
      out.write("<div class=\"container-xxl py-5\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1 class=\"display-5 text-center mb-5 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("      Animal Stories\r\n");
      out.write("    </h1>\r\n");
      out.write("    <div class=\"owl-carousel testimonial-carousel wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("      <div class=\"testimonial-item text-center\">\r\n");
      out.write("        <img class=\"img-fluid rounded-circle border border-2 p-2 mx-auto mb-4\" src=\"img/testimonial-1.png\"\r\n");
      out.write("          style=\"width: 100px; height: 100px\" />\r\n");
      out.write("        <div class=\"testimonial-text rounded text-center p-4\">\r\n");
      out.write("          <p>\r\n");
      out.write("            \"The Indian Elephant, a majestic creature, was saved from poaching thanks to our conservation efforts. \r\n");
      out.write("            Now, they roam freely in protected reserves, helping to maintain the ecosystem balance.\"\r\n");
      out.write("          </p>\r\n");
      out.write("          <h5 class=\"mb-1\">Richard Caines\r\n");
      out.write("</h5>\r\n");
      out.write("          <span class=\"fst-italic\">Director, Environmental and Social Safeguards Appointment</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"testimonial-item text-center\">\r\n");
      out.write("        <img class=\"img-fluid rounded-circle border border-2 p-2 mx-auto mb-4\" src=\"img/testimonial-2.jpg\"\r\n");
      out.write("          style=\"width: 100px; height: 100px\" />\r\n");
      out.write("        <div class=\"testimonial-text rounded text-center p-4\">\r\n");
      out.write("          <p>\r\n");
      out.write("            \"The Golden Langur, once on the brink of extinction, now thrives in our protected habitats. \r\n");
      out.write("            This success story showcases the importance of dedicated conservation efforts and community support.\"\r\n");
      out.write("          </p>\r\n");
      out.write("          <h5 class=\"mb-1\">Nikhil Advani</h5>\r\n");
      out.write("          <span class=\"fst-italic\">Senior Director, Wildlife and Climate Resilience</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"testimonial-item text-center\">\r\n");
      out.write("        <img class=\"img-fluid rounded-circle border border-2 p-2 mx-auto mb-4\" src=\"img/testimonial-3.jpg\"\r\n");
      out.write("          style=\"width: 100px; height: 100px\" />\r\n");
      out.write("        <div class=\"testimonial-text rounded text-center p-4\">\r\n");
      out.write("          <p>\r\n");
      out.write("            \"The Indian One Horned Rhinoceros has made a remarkable comeback from the verge of extinction, \r\n");
      out.write("            thanks to our relentless anti-poaching campaigns and habitat restoration projects.\"\r\n");
      out.write("          </p>\r\n");
      out.write("          <h5 class=\"mb-1\">Marty Spitzer\r\n");
      out.write("</h5>\r\n");
      out.write("          <span class=\"fst-italic\">Senior Director, Climate and Renewable Energy</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "userfooter.jsp", out, false);
      out.write("\r\n");
      out.write("     <script>\r\n");
      out.write("  window.watsonAssistantChatOptions = {\r\n");
      out.write("    integrationID: \"40f6535b-f4fd-4da5-9334-91599b86c0b0\", // The ID of this integration.\r\n");
      out.write("    region: \"au-syd\", // The region your integration is hosted in.\r\n");
      out.write("    serviceInstanceID: \"eab37542-ac5e-4718-8d4f-787f12a29357\", // The ID of your service instance.\r\n");
      out.write("    onLoad: async (instance) => { await instance.render(); }\r\n");
      out.write("  };\r\n");
      out.write("  setTimeout(function(){\r\n");
      out.write("    const t=document.createElement('script');\r\n");
      out.write("    t.src=\"https://web-chat.global.assistant.watson.appdomain.cloud/versions/\" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + \"/WatsonAssistantChatEntry.js\";\r\n");
      out.write("    document.head.appendChild(t);\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
