/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-18 12:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Sign Up Form by WildHaven</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Font Icon -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<!-- Bootstrap CSS for Navbar -->\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link href=\"img/favicon.ico\" rel=\"icon\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Web Fonts -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\"  />\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Quicksand:wght@600;700&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Icon Font Stylesheet -->\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Libraries Stylesheet -->\r\n");
      out.write("  <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("  <link href=\"css1/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Stylesheet -->\r\n");
      out.write("  <link href=\"css1/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" id=\"status\" value=\"");
      out.print(request.getAttribute("status") );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-white fixed-top py-lg-0 px-4 px-lg-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  <a href=\"index.html\" class=\"navbar-brand p-0\">\r\n");
      out.write("    <img class=\"img-fluid me-3\" src=\"img/icon/icon-10.png\" alt=\"Icon\" />\r\n");
      out.write("    <h1 class=\"m-0 text-success\">WildHaven</h1>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse py-4 py-lg-0\" id=\"navbarCollapse\">\r\n");
      out.write("    <form action=\"#\" class=\"hm-searchbox d-flex ms-auto me-3\" id=\"search-form\">\r\n");
      out.write("      <input type=\"text\" placeholder=\"Search Here...\" id=\"search-input\" class=\"form-control me-2\">\r\n");
      out.write("      <button class=\"btn btn-light\" type=\"button\" id=\"voice-search-button\">\r\n");
      out.write("    \r\n");
      out.write("      </button>\r\n");
      out.write("      <button class=\"btn btn-light\" type=\"submit\" id=\"search-button\">\r\n");
      out.write("        <i class=\"fa fa-search\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar-nav ms-auto\">\r\n");
      out.write("      <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("      <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Services</a>\r\n");
      out.write("        <div class=\"dropdown-menu rounded-0 rounded-bottom m-0\">\r\n");
      out.write("          <a href=\"/CrudOperation\" class=\"dropdown-item\">Species Management</a>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">Conservation Areas</a>\r\n");
      out.write("          <a href=\"report.jsp\" class=\"dropdown-item\">Wildlife Reports</a>\r\n");
      out.write("          <a href=\"volunteer.jsp\" class=\"dropdown-item\">Volunteer</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"nav-item dropdown\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Media</a>\r\n");
      out.write("        <div class=\"dropdown-menu rounded-0 rounded-bottom m-0\">\r\n");
      out.write("          <a href=\"Wildlife/index.html\" class=\"dropdown-item\">Blogs</a>\r\n");
      out.write("          <a href=\"Event/index.html\" class=\"dropdown-item\">Events</a>\r\n");
      out.write("    \r\n");
      out.write("          <a href=\"wildlife gallery/index.html\" class=\"dropdown-item\">Photo Gallery</a>\r\n");
      out.write("          <a href=\"Wildlife video/index.html\" class=\"dropdown-item\">Video Gallery</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("     <a href=\"registration.jsp\" class=\"btn btn-success\">Join<i class=\"fa fa-arrow-right ms-3\"></i></a>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Sing in  Form -->\r\n");
      out.write("		<section class=\"sign-in\">\r\n");
      out.write("			<div class=\"container\" style=margin-top:50px;>\r\n");
      out.write("				<div class=\"signin-content\">\r\n");
      out.write("				<div class=\"signup-video\">\r\n");
      out.write("          <figure>\r\n");
      out.write("            <video width=\"650px\" height=\"450px\" autoplay muted loop style=\"background-color: transparent;\">\r\n");
      out.write("              <source src=\"img/Login_Form.mp4\" type=\"video/mp4\">\r\n");
      out.write("     \r\n");
      out.write("            </video>\r\n");
      out.write("          </figure>\r\n");
      out.write("          <a href=\"registration.jsp\" class=\"signup-image-link\"><b style=font-family:verdana;>Create Account</b></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"signin-form\">\r\n");
      out.write("						<h2 class=\"form-title text-success\">Sign in</h2>\r\n");
      out.write("						<form method=\"post\" action=\"login\" class=\"register-form\"\r\n");
      out.write("							id=\"login-form\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"username\"><i\r\n");
      out.write("									class=\"zmdi zmdi-account material-icons-name\"></i></label> <input\r\n");
      out.write("									type=\"text\" name=\"username\" id=\"username\"\r\n");
      out.write("									placeholder=\"Your Email\" />\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"password\"><i class=\"zmdi zmdi-lock\"></i></label> <input\r\n");
      out.write("									type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("									placeholder=\"Password\" />\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"checkbox\" name=\"remember-me\" id=\"remember-me\"\r\n");
      out.write("									class=\"agree-term\" /> <label for=\"remember-me\"\r\n");
      out.write("									class=\"label-agree-term\"><span><span></span></span>Remember\r\n");
      out.write("									me</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group form-button\">\r\n");
      out.write("								<input type=\"submit\" name=\"signin\" id=\"signin\"\r\n");
      out.write("									class=\"form-submit\" value=\"Log in\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("						<div class=\"social-login\">\r\n");
      out.write("							<span class=\"social-label\">Or login with</span>\r\n");
      out.write("							<ul class=\"socials\">\r\n");
      out.write("								<li><a href=\"#\"><i\r\n");
      out.write("										class=\"display-flex-center zmdi zmdi-facebook\"></i></a></li>\r\n");
      out.write("								<li><a href=\"#\"><i\r\n");
      out.write("										class=\"display-flex-center zmdi zmdi-twitter\"></i></a></li>\r\n");
      out.write("								<li><a href=\"#\"><i\r\n");
      out.write("										class=\"display-flex-center zmdi zmdi-google\"></i></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- JS -->\r\n");
      out.write("	<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("	<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var status = document.getElementById(\"status\").value;\r\n");
      out.write("\r\n");
      out.write("if(status==\"failed\"){\r\n");
      out.write("	swal(\"Sorry\",\"Wrong Username or password\",\"error\");\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  <script>\r\n");
      out.write("  window.watsonAssistantChatOptions = {\r\n");
      out.write("    integrationID: \"40f6535b-f4fd-4da5-9334-91599b86c0b0\", // The ID of this integration.\r\n");
      out.write("    region: \"au-syd\", // The region your integration is hosted in.\r\n");
      out.write("    serviceInstanceID: \"eab37542-ac5e-4718-8d4f-787f12a29357\", // The ID of your service instance.\r\n");
      out.write("    onLoad: async (instance) => { await instance.render(); }\r\n");
      out.write("  };\r\n");
      out.write("  setTimeout(function(){\r\n");
      out.write("    const t=document.createElement('script');\r\n");
      out.write("    t.src=\"https://web-chat.global.assistant.watson.appdomain.cloud/versions/\" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + \"/WatsonAssistantChatEntry.js\";\r\n");
      out.write("    document.head.appendChild(t);\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("<!-- This templates was made by Colorlib (https://colorlib.com) -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
