/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-18 12:38:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class thankyou_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "userheader.jsp", out, false);
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thank You!</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background: url(\"img/Thanks.png\") no-repeat center center fixed;\r\n");
      out.write("        background-size: cover; /* Cover the entire viewport while maintaining aspect ratio */\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        height: 100vh; /* Full viewport height */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .balloon {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        border-radius: 50% 50% 40% 40%;\r\n");
      out.write("        background-color: #ff6f61;\r\n");
      out.write("        animation: balloonBurst 3s ease-out forwards;\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .balloon:nth-child(1) {\r\n");
      out.write("        background-color: #ff6f61;\r\n");
      out.write("        width: 50px;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        left: 10%;\r\n");
      out.write("        animation-delay: 0s;\r\n");
      out.write("    }\r\n");
      out.write("    .balloon:nth-child(2) {\r\n");
      out.write("        background-color: #f7c6c7;\r\n");
      out.write("        width: 70px;\r\n");
      out.write("        height: 90px;\r\n");
      out.write("        left: 30%;\r\n");
      out.write("        animation-delay: 0.5s;\r\n");
      out.write("    }\r\n");
      out.write("    .balloon:nth-child(3) {\r\n");
      out.write("        background-color: #6a1b9a;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        animation-delay: 1s;\r\n");
      out.write("    }\r\n");
      out.write("    .balloon:nth-child(4) {\r\n");
      out.write("        background-color: #43a047;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        left: 70%;\r\n");
      out.write("        animation-delay: 1.5s;\r\n");
      out.write("    }\r\n");
      out.write("    .balloon:nth-child(5) {\r\n");
      out.write("        background-color: #039be5;\r\n");
      out.write("        width: 90px;\r\n");
      out.write("        height: 110px;\r\n");
      out.write("        left: 90%;\r\n");
      out.write("        animation-delay: 2s;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes balloonBurst {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: scale(0);\r\n");
      out.write("            top: 0;\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        50% {\r\n");
      out.write("            transform: scale(1.2);\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: scale(1);\r\n");
      out.write("            top: 100vh;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    .confetti {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 10px;\r\n");
      out.write("        height: 10px;\r\n");
      out.write("        background-color: #ffeb3b;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        animation: confettiFall 4s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("    .confetti:nth-child(6) {\r\n");
      out.write("        background-color: #ffeb3b;\r\n");
      out.write("        left: 10%;\r\n");
      out.write("        animation-delay: 0s;\r\n");
      out.write("    }\r\n");
      out.write("    .confetti:nth-child(7) {\r\n");
      out.write("        background-color: #e91e63;\r\n");
      out.write("        left: 25%;\r\n");
      out.write("        animation-delay: 1s;\r\n");
      out.write("    }\r\n");
      out.write("    .confetti:nth-child(8) {\r\n");
      out.write("        background-color: #00bcd4;\r\n");
      out.write("        left: 40%;\r\n");
      out.write("        animation-delay: 2s;\r\n");
      out.write("    }\r\n");
      out.write("    .confetti:nth-child(9) {\r\n");
      out.write("        background-color: #4caf50;\r\n");
      out.write("        left: 55%;\r\n");
      out.write("        animation-delay: 3s;\r\n");
      out.write("    }\r\n");
      out.write("    .confetti:nth-child(10) {\r\n");
      out.write("        background-color: #ff5722;\r\n");
      out.write("        left: 70%;\r\n");
      out.write("        animation-delay: 4s;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes confettiFall {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: translateY(-100%);\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: translateY(100vh);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write(".message {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  background-color: #f0f0f0; /* Optional background color */\r\n");
      out.write("  box-shadow: 0px -2px 5px rgba(0,0,0,0.1); /* Optional shadow for visual effect */\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message h2, \r\n");
      out.write(".message p {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  margin:25px;\r\n");
      out.write("  font-size: 18px; /* Adjust as needed */\r\n");
      out.write("  color:green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" table {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("        table, th, td {\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"message\">\r\n");
      out.write("       <h2>Thank you for your incredible dedication and support in protecting wildlife. Your efforts make a real difference, and we’re grateful to have you as part of our team!</h2>\r\n");
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Name</th>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Address</th>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${address}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Phone Number</th>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phoneNumber}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Your Email ID</th>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <p>We will get in touch with you soon!</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Balloons -->\r\n");
      out.write("    <div class=\"balloon\"></div>\r\n");
      out.write("    <div class=\"balloon\"></div>\r\n");
      out.write("    <div class=\"balloon\"></div>\r\n");
      out.write("    <div class=\"balloon\"></div>\r\n");
      out.write("    <div class=\"balloon\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Confetti -->\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("    <div class=\"confetti\"></div>\r\n");
      out.write("      <!-- Template Javascript -->\r\n");
      out.write("  <script src=\"js1/main.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  window.watsonAssistantChatOptions = {\r\n");
      out.write("    integrationID: \"40f6535b-f4fd-4da5-9334-91599b86c0b0\", // The ID of this integration.\r\n");
      out.write("    region: \"au-syd\", // The region your integration is hosted in.\r\n");
      out.write("    serviceInstanceID: \"eab37542-ac5e-4718-8d4f-787f12a29357\", // The ID of your service instance.\r\n");
      out.write("    onLoad: async (instance) => { await instance.render(); }\r\n");
      out.write("  };\r\n");
      out.write("  setTimeout(function(){\r\n");
      out.write("    const t=document.createElement('script');\r\n");
      out.write("    t.src=\"https://web-chat.global.assistant.watson.appdomain.cloud/versions/\" + (window.watsonAssistantChatOptions.clientVersion || 'latest') + \"/WatsonAssistantChatEntry.js\";\r\n");
      out.write("    document.head.appendChild(t);\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
